### ISSUE TITLE
Tell TASVideos that we now have a new host

### ISSUE THREAD

**Issue by piorrro33** [piorrro33/psxjin#62]
Since I still see issues being created on the Google Code repo, I think it would be a good thing to tell TASVideos that the home of PSXJin has changed. That would be a good thing since it will attract devs to our new page instead of the old, dead repository. Plus, it would be a good thing to be able to do so before our new version gets out, so that we could attract even more people by raising the HYPE!

**Comment by Spikestuff** [comment]
1) https://github.com/TASVideos/psxjin
2) http://tasvideos.org/forum/viewtopic.php?t=16917

**Comment by piorrro33** [comment]
Well, I already told to Adelikat and he "seems" to be having the same opinion than you. And he also sent me these two links ; I've never ever seen the first one before (and it's pretty useless since it has been abandoned) and the second one is pretty sad, yeah. Thankfully, these accuracy tests you did at TASVideos are really useful to know what we have to improve. 

And yes, I was thinking about changing the name of the emulator. But first, we'll have to fix these license issues! #64

**Comment by vgturtle127** [comment]
You guys wanna know what's funny? I actually am a part of the TASVideos GitHub group. :stuck_out_tongue_closed_eyes: 

To be fair, there are better emulators for PS1. However, PSXjin was kind of built for a specific purpose. I kind of like the simplicity it has. I definitely don't like plugin-based emulators. And since this only uses plugins that are essentially built-in to the emulator, that makes it so end users don't have to worry about it.

We should change the name, although I feel like nobody is going to continue the original, so it almost wouldn't matter at that point? I don't know, we will have to see.

Your comment about making into a cycle-accurate emulator made me chuckle. At first I was like, "Oh, as if", but then I thought about it and I realized that while we probably couldn't make it cycle-accurate, we could probably still get great performance and have it play loads of games well without relying on plugins. Although we use plugin code for our emulator's various parts, those are all open-source, so in combination with a default set of plugins configured for most games and a more accurate set of default options, we could potentially create a PS1 emulator without plugins that actually runs games well and has good features like controller support, recording, etc.

Also, PSXjin-Reloaded sounds/looks a lot like PCSX-Reloaded, which I think we should shy away from since Reloaded is used in about every emulator. :laughing: 

I was thinking PSXREGEN sounded OK since it kind of sounds like PSXjin, but looks cooler. :laughing: 

I would try to create a fancy logo, but I can't install Photoshop with 88MB of space left on my hard drive. :laughing: :disappointed:

**Comment by piorrro33** [comment]
"We should change the name, although I feel like nobody is going to 
continue the original, so it almost wouldn't matter at that point?"
No it would matter since it would allow us to remove this bad accuracy 
reputation that PSXJin inherited because of PCSX.
PSXREGEN sounds good though.

"in combination with a default set of plugins configured for most games and 
a more accurate set of default options"
Great idea, it's a bit like BizHawk and its presets.

"I would try to create a fancy logo, but I can't install Photoshop with 
88MB of space left on my hard drive."
Well, since I'm in holidays until Monday, I can't really help you until 
then. But after Monday 27th, no problem.

**Comment by vgturtle127** [comment]
Alright, I will see if I can find an online photo editor and maybe whip up a prototype logo for PSXREGEN. :smile: 

I actually have to be out of town as well, although I am going to a funeral.

But your idea about BizHawk is spot on. I actually have never tried BizHawk. I tried to run it when it was just getting started, and it failed a lot and there were bugs and glitches everywhere. I remember I ran it once and it worked, but I didn't try any games or anything, but I kept it up to date for some reason. So I have the latest version, but I haven't run any games with it. So I guess I should try it since it is taking up space on my hard drive. :laughing:

**Comment by piorrro33** [comment]
1) Great, it'll tell me a bit what the logo would look like. 
2) Ok :disappointed: 
3) Yes you should try it. I recommend you to try it with an SNES ROM since the SNES emulation of bsnes is 100% accurate to the SNES (yes really 100%)

**Comment by vgturtle127** [comment]
Here is an extremely rough draft that I made in like 5 minutes:

![test](https://cloud.githubusercontent.com/assets/3183676/8793211/211a7d66-2f39-11e5-9f61-aa226f179005.png)

**Comment by piorrro33** [comment]
The text doesn't look that bad, but it would be a good idea to make something "flat design", that'd be cool.

**Comment by vgturtle127** [comment]
I'll try that and see how it looks.

**Comment by piorrro33** [comment]
Make everything flat. :smile:

**Comment by vgturtle127** [comment]
Oh OK. :laughing: 

I am in the process of flattening everything. :stuck_out_tongue:

**Comment by piorrro33** [comment]
Great great :)

**Comment by piorrro33** [comment]
So, how's it going?

**Comment by vgturtle127** [comment]
If you mean the logo, I saved it but I haven't uploaded it yet. Here is the WIP version I did:

![test2](https://cloud.githubusercontent.com/assets/3183676/9023574/85d9da22-3866-11e5-9019-0efa491fbdfd.png)

If you mean everything else, I was doing some Lua changes when my power went out all of the sudden, and I freaked out. I forgot I was moving in a few days, and they turned my power off early. :cry: 

After that, I was trying to get everything back to normal when my internet was shut off. I assumed it was another premature shut off, and it was. I have to move in like a day, so I decided it was best to see if I could move first so I don't lose any work that I did.

I should have internet, power, and my computer setup by Monday. If everything goes according to plan.

Other than that, I think the issue with Lua is in the PSXjin implementation. We can upgrade to the latest version in the current version (5.1.x, I think?), and then we can decide other things we want to change before continuing with any Lua stuff.

If I have to look at any more Lua code or anything, I swear I will explode. :laughing:

**Comment by piorrro33** [comment]
Ok no problem. I hope you'll be back up working ASAP! By the way, I can't code much for now since I don't have a computer ATM, just my phone and my Wii. :laughing: I should be able to get a computer on Saturday if everything goes well. 
About Lua, I also thought that was because of PSXJin since I saw that the code was pretty crappy. 
About the logo, well, I don't like its colors, I'd prefer something more "flashy", if you see what I mean. ;) 
Well, have fun moving :smiley:

**Comment by vgturtle127** [comment]
Yeah, I suck at logo design. :laughing: 

We will be moving various things for about a week or so. I still can post on GitHub I suppose, but there may be times when I don't have power or internet. Hopefully they will be short.

Moving isn't very fun when you have to do it all yourself. :laughing:

**Comment by piorrro33** [comment]
Oh, take your time, don't worry. By the way, could you please add me on 
Skype? I added your 2 accounts though you didn't add me on none of the 2 
accounts. BibleThump

**Comment by piorrro33** [comment]
Here's my version of the logo.
![psxregen-logo](https://cloud.githubusercontent.com/assets/6281092/9254817/cc275ad0-41e5-11e5-9aee-5180c1b999e9.png)

**Comment by vgturtle127** [comment]
So I'm back finally. :laughing: 

Sorry about the long wait. I won't try to make excuses, but basically some life stuff happened and I didn't have internet or a computer for a long time. Again, I apologize. Hopefully when I make my return video and post it on YouTube everybody will understand.

That is so much better than my logo! Not only that, it is way more colorful and it matches the PlayStation color scheme! I like the controller and text way better too. Just great. :smile: 

My birthday is coming up and hopefully I will get some cash so I can get an external hard drive and get all the stuff off of all my devices and computers and get them in a central location. After that, I will upgrade to Windows 10 Pro. I upgraded all the other PC's in my house and I have to say it is way better than Windows 8.1.

I have been making some small changes to PSXjin, and I will hopefully have some commits ready in the near future. I still have to upgrade Notepad++ and change from GitHub for Windows to GitHub Desktop. And make sure all that goes smoothly.

I have some other proposed changes to either discuss or just commit, like updating the repo to use the license system from PCSX2, and some new discoveries brought to my attention thanks to the TASvideos.org community and the BizHawk team. :smile: 

Anyway, I am finally going to return to work. :+1:

**Comment by piorrro33** [comment]
Ah great, great! I almost thought you were dead. No worries, I can understand.
Nice to see that you're back and that you liked my logo. I also hope you'll 
get enough money for a new drive. About Notepad++, I heard that UltraEdit 
was better for coding. Just heard that.
About the license system. Ah, that license system... Please, try not to 
fuck up everything like the last time. 😂
I still can't bear GitHub Desktop personally so I only use TortoiseGit and 
Git for Windows.
Anyway, nice to see you back around :)
Next commit of mine : update the logo.

**Comment by vgturtle127** [comment]
Well, the licensing things I want to do are to prevent future things like that from happening. Basically, similar to PCSX2, we will have a docs directory where we will keep licenses, all of the contributors, and also a list of original authors and other teams. That way everybody is happy. I will also probably include a list of libraries and code we use, again to avoid problems. :heavy_check_mark: 

And in reality, I didn't do anything that would have messed anything up in the long run. It was more cosmetic and unwritten rule type stuff. Had we never changed it, if anything we could still have just changed it. I still need to go back and make sure all the headers have the right license version, because one had GNU LGPL v2.1 and it was actually GNU GPL v2. Whatever, regardless it won't be an issue further. :pray: 

Most importantly I have gotten my hands on some PS1 emulation accuracy tests and some homebrew tech demos and SDK testing applications so that I can see what kind of additions or changes we need to make to make it more accurate. Thankfully, making it faster and easier to use is simpler, since all we have to do is ask ourselves what we want and then write the code. :smile: 

I still need to fix Lua, but the problem is not only are there reported problems with the version of Lua we are using, but the newer versions in the same version tree AND in the newer upgrade versions all have some compatibility issues. They should be somewhat simple, but I am trying to contact the Lua team to see what they say, or if other projects have had the same problem.

Lastly, I think everybody thought I was dead. I haven't spoken to some of my friends in a year or two, and I have been on and off internet entirely for a few months. As I said before, I hope I will be able to explain in a week or two. A LOT has happened. Some really exciting stuff, some sad, some happy, some infuriating stuff, but in the end I can't wait for the future. :smile:

**Comment by piorrro33** [comment]
About the license folder, I think that's a good idea. It'd clean up the 
repo but also make everyone happy. +1 I don't know much about these files, 
so I'll let you check them.

About the accuracy tests, I guess we have the same ones, including some in 
PS-EXE format. The problem is that the option to run PS-EXE has been 
removed from PSXJin for whatever reason. We'll have to investigate this 
issue. #66

About Lua, I really don't know what I can do to help you to fix Lua, so I 
guess I'll just let you take that. I'm too bad at deving. :(

About the fact that you were dead, to be honest, I also thought you were, 
or that you completely stopped using GitHub. These were the two 
possibilities I thought of.

About the logo, since you seem to like it, I'll replace PSXJin's.

P.S. We need a real place to talk, this issue page is not a good place. Add 
me on Skype : Piorrro33.

**Comment by piorrro33** [comment]
Solved -> closed.
